name: Goodreads Scraper

on:
  schedule:
    # Runs on the 1st of each month at 12:00 UTC (8:00 AM ET)
    - cron: "0 12 1 * *"
  workflow_dispatch:  # allows manual run
    inputs:
      reason:
        description: "Reason for manual run"
        required: false
        default: "Manual trigger"

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 gspread oauth2client

      - name: Add Google Service Account JSON
        env:
          GOOGLE_SA_JSON: ${{ secrets.GOOGLE_SA_JSON }}
        run: |
          echo "$GOOGLE_SA_JSON" > sa.json

      - name: Run Goodreads scraper
        env:
          GSPREAD_SHEET_ID: ${{ secrets.GSPREAD_SHEET_ID }}
        run: |
          python goodreads_scraper.py

      - name: Commit logs (optional)
        if: always()
        run: |
          mkdir -p logs
          echo "Run completed at $(date)" > logs/goodreads_run.log
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add logs/goodreads_run.log || true
          git commit -m "Add Goodreads run log" || echo "No changes to commit"
          git push || echo "No push needed"
