name: MindBodyGreen RSS Generator

on:
  schedule:
    - cron: "0 12 1 * *"   # Run at 12:00 UTC on the 1st of each month
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 feedgen

      - name: Generate MindBodyGreen RSS feed
        run: python scripts/mindbodygreen_feedgen.py

      - name: Commit and push feed update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add feeds/mindbodygreen_feed.xml
          git commit -m "Automated MindBodyGreen RSS feed update" || echo "No changes to commit"
          git push
