name: TinyBuddha Scraper

on:
  schedule:
    - cron: "0 14 1 * *"  # 1st of each month at 14:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tiny Buddha scraper
        env:
          GOOGLE_SA_JSON: ${{ secrets.GOOGLE_SA_JSON }}
        run: |
          echo "$GOOGLE_SA_JSON" > sa.json
          python scripts/tinybuddha_scraper.py
