name: ZenQuotes Monthly Pull

on:
  schedule:
    - cron: "0 13 1 * *"   # 13:00 UTC = 08:00 CT (CST/CDT handled by UTC)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          GOOGLE_SA_JSON: ${{ secrets.GOOGLE_SA_JSON }}
          GSPREAD_SHEET_ID: ${{ secrets.GSPREAD_SHEET_ID }}
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
        run: |
          python scripts/pull_zenquotes.py

      - name: Commit CSV changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.csv || true
          if ! git diff --cached --quiet; then
            git commit -m "chore(zenquotes): monthly pull $(date -I)"
            git push
          else
            echo "No CSV changes to commit."
          fi
